version: "3.7"

services:

  httpd:
    build:
      context: ./services/httpd
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./public
        target: /usr/local/apache2/htdocs
    depends_on:
      - php

  php:
    build:
      context: ./services/php
    volumes:
      - type: bind
        source: ./public
        target: /usr/local/apache2/htdocs
